exception.message.GENERIC_EXCEPTION=An error occurred while processing the request. Specific exception code message does not found.
exception.message.ENTITY_NOT_FOUND_EXCEPTION={0} not found.
exception.message.ENTITY_ALREADY_EXISTS_EXCEPTION=Record already exist.
exception.message.TRAINER_WORKLOAD_NOT_FOUND_EXCEPTION=No workload data available for trainer.
exception.message.PASSWORD_MISMATCH_EXCEPTION=The old password you entered is incorrect.
exception.message.USER_MISMATCH_EXCEPTION=User validation failed.
exception.message.USER_LOCKED_EXCEPTION=Account blocked for 5 minutes due to failed attempts.
